swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Specify possible API endpoints for Argent Bank development phase 2 (concerning transactions)
  version: 1.0.0
  termsOfService: 'http://swagger.io/terms'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /account/transactions:
    get:
      security:
        - Bearer: [ ]
      tags:
        - User Transactions
      summary: User Transactions for current month
      description: API to get all transactions for current month
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attached Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountId
          description: User's account Id
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions successfully retrieved
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404' :
          description: Not Found
        '500':
          description: Internal Server Error

  /account/transactions/{transactionId}:
    get:
      security:
        - Bearer: [ ]
      tags:
        - User Transactions
      summary: Transaction details
      description: API for getting single transaction details
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attached Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountId
          description: User's account Id
          required: true
        - in: path
          type: string
          name: transactionId
          description: Transaction's Id
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction successfully retrieved
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: [ ]
      tags:
        - User Transactions
      summary: Partially Update transaction
      description: Update transaction's details and category
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attached Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountId
          description: User's account Id
          required: true
        - in: path
          type: string
          name: transactionId
          description: Transaction's Id
          required: true
        - in: body
          name: body
          description: Partial Update transaction attributes (description and category)
          required: true
          schema:
            $ref: '#/definitions/TransactionDetail'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction successfully retrieved
          schema:
            $ref: '#/definitions/TransactionDetail'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

    delete:
      security:
        - Bearer: [ ]
      tags:
        - User Transactions
      summary: Delete Transaction Information's
      description: Delete Transaction Information's
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attached Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountId
          description: User's account Id
          required: true
        - in: path
          type: string
          name: transactionId
          description: Transaction's Id
          required: true
        - in: body
          name: body
          description: Partial Delete transaction attribute (description)
          required: true
          schema:
            $ref: '#/definitions/TransactionDetailDesc'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction successfully retrieved
          schema:
            $ref: '#/definitions/TransactionDetailDesc'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transactions:
    type: object
    properties:
      transactionId:
        type: string
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      category:
        type: string
  TransactionDetail:
    type: object
    properties:
      description:
        type: string
      category:
        type: string
  TransactionDetailDesc:
    type: object
    properties:
      description:
        type: string


